const $=id=>document.getElementById(id),fmt=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});let ownerType="pj",seq=0;
function d(s){return(s||"").replace(/\D/g,"")}function cpfMask(s){let x=d(s).slice(0,11);return x.length>9?x.slice(0,3)+"."+x.slice(3,6)+"."+x.slice(6,9)+"-"+x.slice(9):x.length>6?x.slice(0,3)+"."+x.slice(3,6)+"."+x.slice(6):x.length>3?x.slice(0,3)+"."+x.slice(3):x}
function cpfOk(s){let x=d(s);if(x.length!=11||/^([0-9])\1{10}$/.test(x))return false;let z=0;for(let i=0;i<9;i++)z+=+x[i]*(10-i);let a=z*10%11;a=a==10?0:a;if(a!=+x[9])return false;z=0;for(let i=0;i<10;i++)z+=+x[i]*(11-i);a=z*10%11;a=a==10?0:a;return a==+x[10]}
[["ownerCpf","ownerCpfStatus"],["ownerPfCpf","ownerPfCpfStatus"],["tenantCpf","tenantCpfStatus"]].forEach(([i,s])=>{$(i).oninput=()=>$(i).value=cpfMask($(i).value);$(i).onblur=()=>{let ok=cpfOk($(i).value),e=$(s);e.textContent=$(i).value?(ok?"✓ CPF válido":"✕ CPF inválido"):"";e.className="status "+(ok?"ok":"bad")}});
["w1Cpf","w2Cpf"].forEach(i=>$(i).oninput=()=>$(i).value=cpfMask($(i).value));
function cepMask(s){let x=d(s).slice(0,8);return x.length>5?x.slice(0,5)+"-"+x.slice(5):x}
function cep(prefix,id){$(id).oninput=()=>$(id).value=cepMask($(id).value);$(id).onblur=()=>{let x=d($(id).value);if(x.length!=8)return;fetch("https://viacep.com.br/ws/"+x+"/json/").then(r=>r.json()).then(v=>{if(v.erro)return;["Street","Bairro","City","Uf"].forEach((k,j)=>$(prefix+k).value=[v.logradouro,v.bairro,v.localidade,v.uf][j]||"")})}}
cep("owner","ownerCep");cep("tenant","tenantCep");cep("property","propertyCep");
document.querySelectorAll("[data-owner-type]").forEach(b=>b.onclick=()=>{ownerType=b.dataset.ownerType;document.querySelectorAll(".pill").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("ownerPJ").classList.toggle("hidden",ownerType!="pj");$("ownerPF").classList.toggle("hidden",ownerType!="pf")});
function dates(){let a=$("checkin").value,b=$("checkout").value,s=$("dateStatus");if(!a||!b)return true;let n=(new Date(b)-new Date(a))/86400000;if(n<=0){$("nights").value="";s.textContent="✕ Check-out precisa ser posterior ao check-in.";s.className="status bad";return false}$("nights").value=n;s.textContent="✓ "+n+" diária(s).";s.className="status ok";return true}
$("checkin").onchange=()=>{$("checkout").min=$("checkin").value;dates()};$("checkout").onchange=dates;
function money(){let r=+$("rentValue").value||0,c=+$("cleanValue").value||0,q=+$("commissionPct").value||0,s=+$("reservationValue").value||0;$("totalValue").textContent=fmt.format(r+c);$("commissionValue").textContent=fmt.format(r*q/100);$("balanceValue").textContent=fmt.format(Math.max(0,r-s))}["rentValue","cleanValue","commissionPct","reservationValue"].forEach(i=>$(i).oninput=money);money();
$("btnAddInstallment").onclick=()=>{if(document.querySelectorAll(".installment").length>=3)return alert("Limite de 3 parcelas adicionais.");seq++;let x=document.createElement("div");x.className="installment";x.innerHTML='<div class="installment-title"><b>PARCELA '+seq+'</b><button type="button" class="remove">Remover</button></div><div class="grid"><div class="field c6"><label>Vencimento</label><input class="pdate" type="date"></div><div class="field c6"><label>Valor (R$)</label><input class="pvalue" type="number" step="0.01" min="0"></div></div>';x.querySelector(".remove").onclick=()=>{x.remove();renum()};$("installments").appendChild(x)};function renum(){document.querySelectorAll(".installment").forEach((x,i)=>x.querySelector("b").textContent="PARCELA "+(i+1))}
function v(i){return($(i).value||"").trim()}function br(s){let p=s.split("-");return p[2]+"/"+p[1]+"/"+p[0]}function addr(p){return[v(p+"Street"),v(p+"Number"),v(p+"Comp"),v(p+"Bairro"),v(p+"City"),v(p+"Uf"),v(p+"Cep")].filter(Boolean).join(", ")}
function owner(){return ownerType=="pf"?v("ownerPfName")+", "+v("ownerPfCivil")+", "+v("ownerPfJob")+", RG "+v("ownerPfRg")+" e CPF "+v("ownerPfCpf"):v("ownerName")+", CNPJ "+v("ownerCnpj")+" Representante legal: "+v("ownerRep")+", RG "+v("ownerRg")+" e CPF "+v("ownerCpf")}
function paragraph(doc,title,text,state){let w=170,lines=doc.splitTextToSize(title+text,w);if(state.y+lines.length*5.2>270){doc.addPage();state.y=20}doc.setFont("helvetica","normal");if(title){doc.setFont("helvetica","bold");doc.text(title,20,state.y);doc.setFont("helvetica","normal");let tw=doc.getTextWidth(title);doc.text(doc.splitTextToSize(text,w-tw),20+tw,state.y);state.y+=Math.max(1,doc.splitTextToSize(text,w-tw).length)*5.2}else{doc.text(lines,20,state.y);state.y+=lines.length*5.2}state.y+=3}
function footer(doc){doc.setFontSize(8);doc.setFont("helvetica","bold");doc.text("E. Bronca Corretora de Imóveis",105,284,{align:"center"});doc.setFont("helvetica","normal");doc.text("CRECI: 199.167-F | Estrada Mario de Moraes 1033 casa 1, Juquehy, São Sebastião/SP | (12) 98123-5534",105,288,{align:"center"});doc.setFontSize(10)}
function pdf(){if(!dates())return alert("Corrija as datas antes de gerar.");if(!window.jspdf||!window.jspdf.jsPDF)return alert("O motor de PDF não foi carregado. No Brave, permita o script externo usado pelo gerador (jsDelivr) para gerar o arquivo PDF.");let c=cpfOk(v("tenantCpf"));if(v("tenantCpf")&&!c)return alert("CPF do locatário inválido.");if(!v("tenantName")||!v("propertyStreet")||!v("checkin")||!v("checkout"))return alert("Preencha nome do locatário, imóvel e datas.");let J=window.jspdf.jsPDF,doc=new J({unit:"mm",format:"a4"}),s={y:23};doc.setFont("helvetica","bold");doc.setFontSize(14);doc.text("CONTRATO DE ALUGUEL DE TEMPORADA",105,s.y,{align:"center"});s.y+=14;doc.setFontSize(10);
paragraph(doc,"LOCADOR: ",owner()+" domiciliado em "+addr("owner")+".",s);
paragraph(doc,"LOCATÁRIO: ",v("tenantName")+", "+v("tenantCivil")+", "+v("tenantJob")+", portador do RG "+v("tenantRg")+" e inscrito no CPF: "+v("tenantCpf")+", residente e domiciliado à "+addr("tenant")+", E-mail: "+v("tenantEmail")+".",s);
paragraph(doc,"IMÓVEL: ",addr("property")+(v("propertyCondo")?" "+v("propertyCondo"):"")+".",s);
paragraph(doc,"PRAZO: ",v("nights")+" ( "+v("nights")+" ) diárias, iniciando a partir das "+v("checkinTime")+" horas do dia "+br(v("checkin"))+" sendo a saída no dia "+br(v("checkout"))+" até as "+v("checkoutTime")+" horas, oportunidade em que o LOCATÁRIO devolverá as chaves na "+v("keyPlace")+", obrigando-se a restituir o imóvel locado no perfeito estado de conservação em que o recebeu. Será incluso no valor total desta locação, a taxa de limpeza de "+fmt.format(+$("cleanValue").value||0)+" que será depositada junto com o valor de reserva do imóvel.",s);
let rent=+$("rentValue").value||0,clean=+$("cleanValue").value||0,total=rent+clean,com=rent*(+$("commissionPct").value||0)/100;
paragraph(doc,"VALOR: ","R$ "+total.toLocaleString("pt-BR",{minimumFractionDigits:2})+" (sendo R$ "+rent.toLocaleString("pt-BR",{minimumFractionDigits:2})+" de locação e R$ "+clean.toLocaleString("pt-BR",{minimumFractionDigits:2})+" de limpeza).",s);
paragraph(doc,"RESERVA: ","R$ "+(+$("reservationValue").value||0).toLocaleString("pt-BR",{minimumFractionDigits:2})+" pagos na data de assinatura deste contrato na conta do locador "+v("ownerPayment")+".",s);
document.querySelectorAll(".installment").forEach((x,i)=>paragraph(doc,"PARCELA "+(i+1)+": ","R$ "+((+x.querySelector(".pvalue").value)||0).toLocaleString("pt-BR",{minimumFractionDigits:2})+" pagos até a data "+br(x.querySelector(".pdate").value)+" na conta do locador "+v("ownerPayment")+".",s));
paragraph(doc,"","Os comprovantes dos depósitos servirão como recibo do pagamento.",s);
paragraph(doc,"Parágrafo 1: ","Não cumprido pagamento nas datas estabelecidas acima ensejará uma multa de "+v("lateFinePct")+"% do valor da parcela inadimplida.",s);
paragraph(doc,"CAUÇÃO: ","Desde já, fica estabelecido que ao efetuar o check-in o locatário deixará em responsabilidade do corretor um cheque caução de "+fmt.format(+$("cautionValue").value||0)+" que será devolvido após vistoria do imóvel e constatação da integridade do imóvel.",s);
paragraph(doc,"Parágrafo 1: ","deve ser enviado uma foto do cheque que será dado como caução no ato da assinatura desse contrato para consulta e análise, que poderá ser recusado caso o CPF esteja com restrição nos órgão de defesa do consumidor.",s);
paragraph(doc,"RESCISÃO: ","O presente contrato destina-se única e exclusivamente para fins de aluguel de temporada, sendo intransferível, não podendo o imóvel ser sublocado, cedido ou emprestado, sob qualquer pretexto, tendo a sua rescisão automática no dies a quo.",s);
paragraph(doc,"DESISTÊNCIA: ","Em caso de desistência do LOCATÁRIO, a título de ressarcimento pelos danos oriundos da desistência, o mesmo perderá os valores que já pagou, comprometendo-se a efetuar o pagamento do valor integral do contrato, caso o LOCADOR não consiga alugar o imóvel para o mesmo período.",s);
paragraph(doc,"CAPACIDADE: ","O imóvel locado, pelo seu sistema hidráulico, comporta a habitação máxima de "+v("capacity")+" pessoas. Se o LOCATÁRIO exceder a este número, os que excederem pagarão uma multa diária de "+fmt.format(+$("excessPersonFine").value||0)+" por pessoa, independente das providências de desocupação imediata que poderão ser tomadas a critério do LOCADOR.",s);
paragraph(doc,"CLÁUSULA PENAL: ","A permanência no imóvel após o dies a quo implicará no pagamento em dobro do aluguel, por dia que exceder, até a sua efetiva desocupação. Em casos supervenientes que determinem a antecipação da saída do imóvel pelo LOCATÁRIO, de nenhuma forma será devolvida a quantia já paga.",s);
paragraph(doc,"RESPONSABILIDADE: ","O LOCATÁRIO será responsável por qualquer multa que der causa, seja por desrespeito às leis federais, estaduais, municipais, e condominiais. A responsabilidade também se estende aos danos que causar ao imóvel, que deverão ser imediatamente reparados pelo mesmo.",s);
paragraph(doc,"CONDIÇÕES LEGAIS: ","Rege-se o presente contrato, naquilo em que for omisso, pela Lei n° 8245/91 e lei 12.112/2009 (lei do inquilinato), Código Civil e demais disposições pertinentes à locação de imóveis, direito de vizinhança e etc.",s);
paragraph(doc,"CORRETAGEM E COMISSÃO DE CORRETAGEM: ","O valor pago a título de comissão de corretagem, de "+v("commissionPct")+"% do valor total de locação, é de responsabilidade do proprietário do imóvel, no valor de "+fmt.format(com)+", conforme conta do corretor: "+v("brokerPayment")+".",s);
paragraph(doc,"FORO: ","Para dirimir eventuais controvérsias relacionadas a este contrato, elegem as partes o fórum da "+v("forum")+", renunciando a qualquer outro, por mais especial que seja.",s);
paragraph(doc,"DESPESAS JUDICIAIS: ","Se em razão do descumprimento de uma das cláusulas do presente contrato o LOCADOR fique obrigado a recorrer à tutela do Poder Judiciário, o LOCATÁRIO arcará com o pagamento integral das despesas e custas judiciais, assim como honorários advocatícios, na base de "+v("lawyerPct")+"% sob o valor da causa.",s);
s.y=Math.max(s.y,255);paragraph(doc,"",v("propertyCity")||"São Sebastião"+"/SP, "+longToday()+".",s);
s.y+=7;doc.text("______________________________    ______________________________",20,s.y);s.y+=5;doc.text("LOCADOR                                  LOCATÁRIO",20,s.y);s.y+=12;doc.text("TESTEMUNHAS:",20,s.y);s.y+=9;doc.text("1ª____________________________    2ª____________________________",20,s.y);s.y+=5;doc.text("RG                                  RG",20,s.y);s.y+=5;doc.text("CPF                                 CPF",20,s.y);footer(doc);doc.save("Contrato_Temporada_"+(v("tenantName").replace(/\s+/g,"_")||"EBIMOB")+".pdf")}
function longToday(){let d=new Date();return d.getDate()+" de "+["janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"][d.getMonth()]+" de "+d.getFullYear()}
function preview(){alert("Pré-visualização rápida: revise os campos e clique em Gerar PDF.")}
["btnGerarTop","btnGerarBottom"].forEach(id=>$(id).onclick=pdf);$("btnPreview").onclick=preview;$("btnLimpar").onclick=()=>{if(confirm("Limpar todos os campos?"))location.reload()};